# Exp 2

### 06219109 孙寒石

### 编写用追赶法解三对角线性方程的程序，并解下列方程组：
$Ax=b$，其中
$$A_{10\times 10}=\left[ \matrix{-4 & 1 &&&&\\1 & -4 & 1 &&&\\&1 & -4& 1 &&\\&& \ddots &\ddots &\ddots & \\&&& 1&-4&1\\ &&&& 1& -4} \right] ,\qquad b=\left[ \matrix{-27\\ -15\\ -15\\ \vdots \\ -15\\ -15} \right]$$

In [1]:
import numpy as np

In [2]:
# 追赶法求三对角线性方程组 
# a 为主对角线元素，bb，c分别为次对角线元素，x为解
def solution(A,b):
    n = A.shape[0]
    a = np.array([])
    bb = np.array([])
    c = np.array([])
    
    a = np.append(a,A[0,0])
    bb = np.append(bb,0)
    c = np.append(c,A[0,1])
    for i in range(n-2):
        a = np.append(a,A[i+1,i+1])
        bb = np.append(bb,A[i+1,i])
        c = np.append(c,A[i+1,i+2])
    a = np.append(a,A[n-1,n-1])
    bb = np.append(bb,A[n-1,n-2])
    c = np.append(c,0)
    
    l = np.array([])
    beta = np.array([])
    y = np.array([])
    beta = np.append(beta,a[0])
    y = np.append(y,b[0])
    l = np.append(l,0)
    for i in range(n-1):
        l = np.append(l,bb[i+1]/beta[i])
        beta = np.append(beta,a[i+1]-l[i+1]*c[i])
        y = np.append(y,b[i+1]-l[i+1]*y[i])
    
    x = np.array([])
    for i in range(n):
        x = np.append(x,0)
    
    x[n-1] = y[n-1]/beta[n-1]
    for i in range(n-1):
        x[n-2-i] = (y[n-2-i] - c[n-2-i]*x[n-2-i+1])/beta[n-2-i]
    return x

In [3]:
A = np.array([[-4,1,0,0,0,0,0,0,0,0],
              [1,-4,1,0,0,0,0,0,0,0],
              [0,1,-4,1,0,0,0,0,0,0],
              [0,0,1,-4,1,0,0,0,0,0],
              [0,0,0,1,-4,1,0,0,0,0],
              [0,0,0,0,1,-4,1,0,0,0],
              [0,0,0,0,0,1,-4,1,0,0],
              [0,0,0,0,0,0,1,-4,1,0],
              [0,0,0,0,0,0,0,1,-4,1],
              [0,0,0,0,0,0,0,0,1,-4]])

In [4]:
A.shape

(10, 10)

In [5]:
A

array([[-4,  1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1, -4,  1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1, -4,  1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1, -4,  1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -4,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  1, -4,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  1, -4,  1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  1, -4,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  1, -4,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1, -4]])

In [6]:
b = np.array([-27,-15,-15,-15,-15,-15,-15,-15,-15,-15])

In [7]:
b.shape

(10,)

In [8]:
b

array([-27, -15, -15, -15, -15, -15, -15, -15, -15, -15])

In [9]:
x = solution(A,b)

In [10]:
x

array([8.70575808, 7.82303234, 7.58637127, 7.52245276, 7.50343976,
       7.4913063 , 7.46178542, 7.35583538, 6.9615561 , 5.49038903])

## Conclusion

#### 所以解得 $$x=\left[ \matrix{8.70575808\\ 7.82303234\\ 7.58637127\\ 7.52245276\\ 7.50343976\\
       7.4913063 \\ 7.46178542\\ 7.35583538\\ 6.9615561\\ 5.49038903} \right]$$